package syntax.com.playground

class DataSource {

    private val someText = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups."
    fun loadShips(): List<Ship> {
        return listOf(
            Ship(R.drawable.ship_01, someText),
            Ship(R.drawable.ship_02, someText),
            Ship(R.drawable.ship_03, someText),
            Ship(R.drawable.ship_04, someText),
            Ship(R.drawable.ship_05, someText),
            Ship(R.drawable.ship_06, someText),
            Ship(R.drawable.ship_07, someText),
            Ship(R.drawable.ship_08, someText),
            Ship(R.drawable.ship_01, someText),
            Ship(R.drawable.ship_02, someText),
            Ship(R.drawable.ship_03, someText),
            Ship(R.drawable.ship_04, someText),
            Ship(R.drawable.ship_05, someText),
            Ship(R.drawable.ship_06, someText),
            Ship(R.drawable.ship_07, someText),
            Ship(R.drawable.ship_08, someText),
            Ship(R.drawable.ship_01, someText),
            Ship(R.drawable.ship_02, someText),
            Ship(R.drawable.ship_03, someText),
            Ship(R.drawable.ship_04, someText),
            Ship(R.drawable.ship_05, someText),
            Ship(R.drawable.ship_06, someText),
            Ship(R.drawable.ship_07, someText),
            Ship(R.drawable.ship_08, someText),
            Ship(R.drawable.ship_01, someText),
            Ship(R.drawable.ship_02, someText),
            Ship(R.drawable.ship_03, someText),
            Ship(R.drawable.ship_04, someText),
            Ship(R.drawable.ship_05, someText),
            Ship(R.drawable.ship_06, someText),
            Ship(R.drawable.ship_07, someText),
            Ship(R.drawable.ship_08, someText),
            Ship(R.drawable.ship_01, someText),
            Ship(R.drawable.ship_02, someText),
            Ship(R.drawable.ship_03, someText),
            Ship(R.drawable.ship_04, someText),
            Ship(R.drawable.ship_05, someText),
            Ship(R.drawable.ship_06, someText),
            Ship(R.drawable.ship_07, someText),
            Ship(R.drawable.ship_08, someText),
            Ship(R.drawable.ship_01, someText),
            Ship(R.drawable.ship_02, someText),
            Ship(R.drawable.ship_03, someText),
            Ship(R.drawable.ship_04, someText),
            Ship(R.drawable.ship_05, someText),
            Ship(R.drawable.ship_06, someText),
            Ship(R.drawable.ship_07, someText),
            Ship(R.drawable.ship_08, someText),
            Ship(R.drawable.ship_01, someText),
            Ship(R.drawable.ship_02, someText),
            Ship(R.drawable.ship_03, someText),
            Ship(R.drawable.ship_04, someText),
            Ship(R.drawable.ship_05, someText),
            Ship(R.drawable.ship_06, someText),
            Ship(R.drawable.ship_07, someText),
            Ship(R.drawable.ship_08, someText),
            Ship(R.drawable.ship_01, someText),
            Ship(R.drawable.ship_02, someText),
            Ship(R.drawable.ship_03, someText),
            Ship(R.drawable.ship_04, someText),
            Ship(R.drawable.ship_05, someText),
            Ship(R.drawable.ship_06, someText),
            Ship(R.drawable.ship_07, someText),
            Ship(R.drawable.ship_08, someText)
        )
    }
}